[2024-06-21T10:55:32.847+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T10:55:32.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-21T10:55:11.587284+00:00 [queued]>
[2024-06-21T10:55:32.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-21T10:55:11.587284+00:00 [queued]>
[2024-06-21T10:55:32.932+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T10:55:33.021+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-06-21 10:55:11.587284+00:00
[2024-06-21T10:55:33.035+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-06-21T10:55:11.587284+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpm_p_ne12']
[2024-06-21T10:55:33.041+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask transform_wikipedia_data
[2024-06-21T10:55:33.045+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=30814) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-21T10:55:33.047+0000] {standard_task_runner.py:63} INFO - Started process 30816 to run task
[2024-06-21T10:55:33.160+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-21T10:55:11.587284+00:00 [running]> on host dd278de8866b
[2024-06-21T10:55:33.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T10:55:11.587284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T10:55:11.587284+00:00'
[2024-06-21T10:55:33.464+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T10:55:40.883+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=New+Administrative+Capital+Stadium+%2C%C2%A0Egypt&format=json&limit=1
[2024-06-21T10:55:50.381+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Jakarta+International+Stadium+%0A%2C%C2%A0Indonesia%0A&format=json&limit=1
[2024-06-21T10:56:14.857+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Millennium+Stadium+%2C%C2%A0Wales&format=json&limit=1
[2024-06-21T10:56:16.867+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89cca16d20>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Millennium+Stadium+%2C%C2%A0Wales&format=json&limit=1
[2024-06-21T10:58:04.817+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Estadio+BBVA%2C%C2%A0Mexico&format=json&limit=1
[2024-06-21T10:58:43.923+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Free+State+Stadium%2C%C2%A0South+Africa&format=json&limit=1
[2024-06-21T10:59:03.944+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Stade+Mohammed+V+%2C%C2%A0Morocco&format=json&limit=1
[2024-06-21T11:00:42.328+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/pipeline/wikipedia_pipeline.py:76 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-06-21T11:00:42.440+0000] {python.py:237} INFO - Done. Returned value was: ok
[2024-06-21T11:00:42.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T11:00:42.526+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, run_id=manual__2024-06-21T10:55:11.587284+00:00, execution_date=20240621T105511, start_date=20240621T105532, end_date=20240621T110042
[2024-06-21T11:00:42.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-21T11:00:42.663+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-21T11:00:42.689+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
