[2024-06-20T05:52:51.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T05:52:51.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-20T05:52:21.662066+00:00 [queued]>
[2024-06-20T05:52:51.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-20T05:52:21.662066+00:00 [queued]>
[2024-06-20T05:52:51.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-20T05:52:51.620+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-06-20 05:52:21.662066+00:00
[2024-06-20T05:52:51.635+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-06-20T05:52:21.662066+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpay6j28tl']
[2024-06-20T05:52:51.641+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask transform_wikipedia_data
[2024-06-20T05:52:51.641+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11015) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T05:52:51.644+0000] {standard_task_runner.py:63} INFO - Started process 11017 to run task
[2024-06-20T05:52:51.783+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-06-20T05:52:21.662066+00:00 [running]> on host dd278de8866b
[2024-06-20T05:52:52.232+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ayush Goswami' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T05:52:21.662066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T05:52:21.662066+00:00'
[2024-06-20T05:52:52.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T05:53:46.099+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Orange+V%C3%A9lodrome%2C%C2%A0France%0A&format=json&limit=1
[2024-06-20T05:54:32.089+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Estadio+Jalisco%2C%C2%A0Mexico&format=json&limit=1
[2024-06-20T05:55:44.453+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Estadio+Libertadores+de+Am%C3%A9rica%2C%C2%A0Argentina%0A&format=json&limit=1
[2024-06-20T05:56:44.749+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Estadio+Hernando+Siles+%2C%C2%A0Bolivia&format=json&limit=1
[2024-06-20T05:56:56.015+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Goodison+Park%0A%2C%C2%A0England%0A&format=json&limit=1
[2024-06-20T05:57:34.767+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Istanbul%0A%2C%C2%A0Turkey&format=json&limit=1
[2024-06-20T05:57:40.522+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/pipeline/wikipedia_pipeline.py:76 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-06-20T05:57:40.752+0000] {python.py:237} INFO - Done. Returned value was: ok
[2024-06-20T05:57:40.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T05:57:40.864+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data, run_id=manual__2024-06-20T05:52:21.662066+00:00, execution_date=20240620T055221, start_date=20240620T055251, end_date=20240620T055740
[2024-06-20T05:57:40.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T05:57:40.996+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T05:57:41.027+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
